import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  phiSidebar: [
    {
      type: 'autogenerated',
      dirName: 'phi',
    },
  ],

  phixumSidebar: [
    {
      type: 'autogenerated',
      dirName: 'phixum',
    },
  ],

  sharedSidebar: [
    {
      type: 'autogenerated',
      dirName: 'shared',
    },
  ],
};

export default sidebars;
