import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * PhiDoc sidebars — data-driven, no hardcoding.
 *
 * Each doc section maps to an autogenerated sidebar from its directory.
 * Brand visual themes (16 puijs brands) are handled client-side
 * by BrandProvider, not as sidebar sections.
 */
const sidebars: SidebarsConfig = {
  phiSidebar: [
    {
      type: 'autogenerated',
      dirName: 'phi',
    },
  ],

  phixumSidebar: [
    {
      type: 'autogenerated',
      dirName: 'phixum',
    },
  ],

  sharedSidebar: [
    {
      type: 'autogenerated',
      dirName: 'shared',
    },
  ],
};

export default sidebars;
